name: KDT CI
 
on:
  push:
    branches: [ master ]
 
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup KDT
        run: |
          curl -sSL https://cli.kondukto.io | sh

      - name: Run a SAST scan
        run: |
          kdt scan --host https://ourfuturehealth.kondukto.io --token cXNVeW5uRnlOVDhrYWplMWtqa251cmxIVm1KTmVPUGwyRkFZelZZU2trZ1VPZFBRekIzN2piSHdrbFV0 -p pygoat-test -t bandit -b master 
