name: Security Analysis

on:
  workflow_dispatch:

jobs:
  codeql:
    name: SAST with sast-scan
    runs-on: ubuntu-latest
    timeout-minutes: 360
    permissions:
      security-events: write
      actions: read
      contents: read

    strategy:
      fail-fast: false
      matrix:
        language: [ 'python' ] 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.0' # Specify the Python version you are using

    - name: Upgrade pip and Install dependencies
      run: |
        python -m venv venv
        . venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}

    # Removed Autobuild for Python as it's not needed for interpreted languages like Python
    # TODO: Might need to get a bit more specific about Python.
    # Example: setup database, migrations, or install dependencies.

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        output: codeql-results.sarif

    - name: Upload SARIF file
      uses: actions/upload-artifact@v2
      with:
        name: CodeQL SARIF Results
        path: codeql-results.sarif
  trivy:
    permissions:
      contents: read 
      security-events: write 
      actions: read 
    name: Build Image & Scan with Trivy
    runs-on: "ubuntu-20.04"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build an image from Dockerfile
        run: |
          docker build -f Dockerfile -t pygoat-image .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: 'pygoat-image'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
      
      - name: Upload SARIF file
        uses: actions/upload-artifact@v2
        with:
          name: Trivy SARIF Results
          path: trivy-results.sarif