name: Security Analysis

on:
  workflow_dispatch:

jobs:
  sast:
    name: SAST with sast-scan
    runs-on: ubuntu-latest
    timeout-minutes: 360
    permissions:
      security-events: write
      actions: read
      contents: read

    strategy:
      fail-fast: false
      matrix:
        language: [ 'python' ] 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}

    # Removed Autobuild for Python as it's not needed for interpreted languages like Python
    # TODO: Might need to get a bit more specific about Python.
    # Example: setup database, migrations, or install dependencies.

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3